### ISSUE TITLE
"\_" key in japanese layout is not working

### ISSUE THREAD

**Issue by X547** [threedeyes/qthaikuplugins#12]
Platform: Haiku hrev53693 gcc2hybrid
Version: 5.14.0-1

When text field is focused, pressing "_" key in japanese layout (most right bottom key) have no effect. This key work in native applications.

**Comment by threedeyes** [comment]
I can't reproduce this bug. Can you show (video for example) how you do it?
I try switch to Japanese layout with Preferences->Keymap and underbar "_" placed on "0" key (with shift).

**Comment by X547** [comment]
I mean this key:
![Layout JP (2)](https://user-images.githubusercontent.com/45505339/71952556-70be0680-3222-11ea-8e8b-2e475a082d66.png)
It is not present in US layout.

https://github.com/X547/HaikuUtils/tree/master/ScreenKeyboard can be used for testing.

**Comment by threedeyes** [comment]
Hmm.
I change keyboard layout in Keymap preflet to Japanese, but i have US layout instead Jp.
![screenshot78](https://user-images.githubusercontent.com/2559260/71978521-493d5d00-3267-11ea-9594-847caf4667bb.png)

**Comment by X547** [comment]
This is Japanese layout. Japanese layout use English alphabet. Try to click bottom "\\" button when text field of some Qt5 application is focused.

**Comment by threedeyes** [comment]
I see, thnx.
It key (107 scancode) not mapped in QPA.
![screenshot79](https://user-images.githubusercontent.com/2559260/71980672-6294d800-326c-11ea-8795-b7cc53c97b48.png)

**Comment by threedeyes** [comment]
Fixed (i hope). Update qthaikuplugins from repo and try again please.

**Comment by X547** [comment]
Fix confirmed.
