### ISSUE TITLE
Flameshot keyboard shortcuts do not work

### ISSUE THREAD

**Issue by fkap69** [threedeyes/qthaikuplugins#13]
In 64bit Haiku hrev53658.

No reaction to "Esc" (should abort capture) or "Enter" (should capture whole screen) or any other shortcut I tried.

**Comment by threedeyes** [comment]
Fixed https://github.com/threedeyes/qthaikuplugins/commit/d3c662a02686849b73051a64b9ca9cb4276b4d08
