### ISSUE TITLE
Can't type some characters in Qt based programs

### ISSUE THREAD

**Issue by extrowerk** [threedeyes/qthaikuplugins#15]
No idea if it something new, but i can't type "í" and "Í" in Qt based programs on Haiku, while it works nicely in native programs.
My current Qt install is: qt5-5.14.0-1-x86_64.hpkg on hrev53652 x86_64

Ref: https://github.com/haikuports/haikuports/issues/4542

**Comment by extrowerk** [comment]
This can be also helpful: qthaikuplugins-5.14.0.4-1-x86_64.hpkg

**Comment by threedeyes** [comment]
What is the keyboard layout? 
Where is the button on the keyboard?

**Comment by extrowerk** [comment]
I use the hungarian layout, the button is on the left side, between the left Shift and Y buttons.

-- Z.

2020.01.11. dátummal, 2:27 időpontban Gerasim Troeglazov <notifications@github.com> írta:

**Comment by threedeyes** [comment]
This key?
![Безымянный](https://user-images.githubusercontent.com/2559260/72197071-f29f7100-3468-11ea-9b6a-b72d73e2e4ca.png)

**Comment by threedeyes** [comment]
It is necessary to find out the scan code of this key.
Download the attached program and run from the terminal. Switch focus to the application window and press buttons to find out the scan code you need.

[TestScanCode_Haiku_x64.zip](https://github.com/threedeyes/qthaikuplugins/files/4048879/TestScanCode_Haiku_x64.zip)

**Comment by extrowerk** [comment]
Yes.

-- Z.

2020.01.11. dátummal, 2:53 időpontban Gerasim Troeglazov <notifications@github.com> írta:

**Comment by threedeyes** [comment]
I think it 0x69 key.
![screenshot89](https://user-images.githubusercontent.com/2559260/72198515-76158e00-347a-11ea-8057-7e2822010a75.png)

**Comment by threedeyes** [comment]
Fixed in https://github.com/threedeyes/qthaikuplugins/commit/4d53cd37b81f2bcfab49f6d34479061a78661da7

Update from repo and try again please.

**Comment by extrowerk** [comment]
Fixed, thanks.
