### ISSUE TITLE
Could not find the Qt platform plugin

### ISSUE THREAD

**Issue by extrowerk** [threedeyes/qthaikuplugins#17]
https://github.com/aliakseis/LIII cannot find the installed plugin.

```
/Ports/Inst/liii> /Ports/Inst/liii/bin/LIII
qt.qpa.plugin: Could not find the Qt platform plugin "haiku" in ""
100% repochecksum-1 [65 bytes]
Validating checksum for Haiku...done.
100% repochecksum-1 [64 bytes]
Validating checksum for HaikuPorts...done.
qthaikuplugins-5.14.0.9-1 from repository system is already installed.
Nothing to do.
/Ports/Inst/liii> /Ports/Inst/liii/bin/LIII
qt.qpa.plugin: Could not find the Qt platform plugin "haiku" in ""
/Ports/Inst/liii> 
```

**Comment by threedeyes** [comment]
The problem is only with this application? Other Qt apps work fine?

**Comment by extrowerk** [comment]
All other Qt program works fine.

**Comment by threedeyes** [comment]
It's code for macos: https://github.com/aliakseis/LIII/blob/master/src/main/main.cpp#L91

Try add this code for haiku:
#ifdef Q_OS_HAIKU
	app.addLibraryPath("/boot/system/add-ons/Qt5");
	app.addLibraryPath("/boot/system/add-ons/x86/Qt5");
#endif

**Comment by extrowerk** [comment]
Thanks, but sadly it doesn't seems to help.

**Comment by threedeyes** [comment]
This project have own qt.conf files in resources.
Try to remove it from resources or fix plugins path on conf files:

https://github.com/aliakseis/LIII/blob/master/resources/qt.conf
https://github.com/aliakseis/LIII/blob/master/resources/LIII/qt.conf

It's not a qthaikuplugins bug.

**Comment by extrowerk** [comment]
Thanks, closing then.
