### ISSUE TITLE
user-properties-groups icon cannot be seen on black background

### ISSUE THREAD

**Issue by KitsuneRal** [threedeyes/qthaikuplugins#22]
I'm posting this on behalf of a Haiku user who won't register on GitHub. While testing [my application](https://github.com/quotient-im/Quaternion), he found that the icon for the "Change room settings..." menu item on the screenshot is invisible. The application takes this icon by `QIcon::fromTheme("user-groups-properties")`.
![image](https://user-images.githubusercontent.com/10569730/106042918-faff3400-60dd-11eb-864e-f1c170a2cc1c.png)
Here it is when the background has a different colour:
![image](https://user-images.githubusercontent.com/10569730/106043211-5a5d4400-60de-11eb-948c-0b00fd9fcb7b.png)

**Comment by threedeyes** [comment]
Fixed in https://github.com/threedeyes/qthaikuplugins/commit/4daa7a13d0dad990c17c31c071ff4af8422c8895
