### ISSUE TITLE
Qt5 plugins for haiku platform

### ISSUE THREAD

**Issue by Begasus** [threedeyes/qthaikuplugins#24]
When checking out the latest version for Strawberry I saw that qsystray-5.15.2.14 is still being used, build is still running.
Just asking if this would make a difference when building Strawberry with Qt6?
**EDIT** well maybe not being used directly, but saw it passing by in the "activated packages"

**Comment by threedeyes** [comment]
qsystray utility used for both - qt5 and qt6. it's ok
