### ISSUE TITLE
Consider splitting icons/ into it's own repository

### ISSUE THREAD

**Issue by ghost** [threedeyes/qthaikuplugins#25]
Now with the gtk3 port on Haiku there is a second potential consumer of the native-looking freedesktop-style svg icons in this repository.
We could split the native looking icons into a seperate repository to make it possible to install the icons as a dependency of gtk3 without pulling in qthaikuplugins.

**Comment by threedeyes** [comment]
It has now been done for a long time. The icons are in a separate package called haiku_svg_icon_theme.
https://depot.haiku-os.org/haiku_svg_icon_theme

**Comment by threedeyes** [comment]
And it is already specified in the dependencies of gtk, qthaikuplugins and qt6_base packages.
For example: https://github.com/haikuports/haikuports/blob/master/x11-libs/gtk3/gtk3-3.24.30.recipe#L35

**Comment by ghost** [comment]
Ah, good. I assumed it was part of qthaikuplugins because it is in this repository.

**Comment by threedeyes** [comment]
It's just historically so. One repository, two different packages.
