### ISSUE TITLE
Support OpenType font

### ISSUE THREAD

**Issue by hanya** [threedeyes/qthaikuplugins#3]
Currently only TrueType font is supported. But some CJK fonts are provided as OpenType font 
such as NotoSansCJKjp-STYLE.otf under /boot/system/data/fonts/otfonts directory. 

In QHaikuPlatformFontDatabase::populateFontDatabase function, please add "*.otf" to the file filter 
to make the otf files detected from the sub directories. Only "*.ttf" is added to the file filter on the current implementation.

**Comment by diversys** [comment]
Could you please create a PR.

**Comment by diversys** [comment]
Closed via 12b60ca7f246e0d55d6c2bcac983c74737366e5a.
